return {
  "hedyhli/outline.nvim",
  lazy = true,
  cmd = { "Outline", "OutlineOpen" },
  keys = {
    { "<leader>o", "<cmd>Outline<cr>", desc = "Toggle Outline" },
  },
  opts = {
    -- Example outline window configuration
    outline_window = {
      position = 'right',
      width = 25,
      relative_width = true,
      auto_close = false,
      auto_jump = false,
      jump_highlight_duration = 300,
      center_on_jump = true,
      show_numbers = false,
      show_relative_numbers = false,
      wrap = false,
      show_cursorline = true,
      hide_cursor = false,
      focus_on_open = false,
      winhl = '',
    },
    outline_items = {
      show_symbol_details = true,
      show_symbol_lineno = false,
      highlight_hovered_item = true,
      auto_set_cursor = true,
      auto_update_events = {
        follow = { 'CursorMoved' },
        items = { 'InsertLeave', 'WinEnter', 'BufEnter', 'BufWinEnter', 'TabEnter', 'BufWritePost' },
      },
    },
    guides = {
      enabled = true,
      markers = {
        bottom = '└',
        middle = '├',
        vertical = '│',
      },
    },
    symbol_folding = {
      autofold_depth = 1,
      auto_unfold_hover = true,
      auto_unfold = {
        only = true,
        hovered = true,
      },
      markers = { '', '' },
    },
    preview_window = {
      auto_preview = false,
      open_hover_on_preview = false,
      width = 50,
      min_width = 50,
      relative_width = true,
      border = 'single',
      winhl = 'NormalFloat:',
      live = false,
    },
    keymaps = {
      show_help = '?',
      close = { '<Esc>', 'q' },
      goto_location = '<Cr>',
      peek_location = 'o',
      goto_and_close = '<S-Cr>',
      restore_location = '<C-g>',
      hover_symbol = '<C-space>',
      toggle_preview = 'K',
      rename_symbol = 'r',
      code_actions = 'a',
      fold = 'h',
      unfold = 'l',
      fold_toggle = '<Tab>',
      fold_toggle_all = '<S-Tab>',
      fold_all = 'W',
      unfold_all = 'E',
      fold_reset = 'R',
    },
    providers = {
      priority = { 'lsp', 'coc', 'markdown', 'norg' },
      lsp = {
        blacklist_clients = {},
      },
    },
    symbols = {
      filter = {
        default = { 'String', exclude = true },
        typescript = {
          'Variable',
          'Class',
          'Function',
          'Method',
          'Constructor',
          'Interface',
          'Module',
          'Struct',
          'Trait',
          'Package',
          'Object',
        },
        javascript = {
          'Variable',
          'Class',
          'Function',
          'Method',
          'Constructor',
          'Interface',
          'Module',
          'Struct',
          'Trait',
          'Package',
          'Object',
        },
      },
      icon_fetcher = function(kind)
        return kind
      end,
      icon_source = nil,
    },
  },
}